In [18]:
import pandas as pd

In [ ]:
df_trailers = pd.read_csv('to_download_trailers.csv')
df_trailers.head()

     imdb_id                       trailer
0  tt0035423  https://youtu.be/6FeyhlLZYrg
1  tt0113026  https://youtu.be/K9Da-XCJvYM
2  tt0113092  https://youtu.be/sc94f2SG0DM
3  tt0118589  https://youtu.be/QaKxGrajnzY
4  tt0118694  https://youtu.be/dWVDZ98AFhI

In [20]:
df = pd.read_csv('movie_dataset.csv')
df.head()

,Unnamed: 0,genres,id,imdb_id,original_language,original_title,overview,production_companies,production_countries,release_date,...,vote_average,vote_count,domestic_distributor,domestic_opening,mpaa,budget,revenue,actors,director,poster
0,0,"['Animation', 'Comedy', 'Family']",862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",['Pixar Animation Studios'],['US'],1995-10-30,...,7.7,5415,Walt Disney Studios Motion Pictures,29140617,NaN,30000000,373554033,"['Tom Hanks', 'Tim Allen', 'Don Rickles']",John Lasseter,https://images-na.ssl-images-amazon.com/images...
1,1,"['Adventure', 'Fantasy', 'Family']",8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,"['TriStar Pictures', 'Teitler Film', 'Intersco...",['US'],1995-12-15,...,6.9,2413,Sony Pictures Releasing,11084370,PG,65000000,262797249,"['Robin Williams', 'Jonathan Hyde', 'Kirsten D...",Joe Johnston,https://images-na.ssl-images-amazon.com/images...
2,2,"['Romance', 'Comedy']",15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,"['Warner Bros.', 'Lancaster Gate']",['US'],1995-12-22,...,6.5,92,Warner Bros.,7797185,PG-13,0,71518503,"['Walter Matthau', 'Jack Lemmon', 'Ann-Margret']",Howard Deutch,https://images-na.ssl-images-amazon.com/images...
3,3,"['Comedy', 'Drama', 'Romance']",31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",['Twentieth Century Fox Film Corporation'],['US'],1995-12-22,...,6.1,34,Twentieth Century Fox,14126927,R,16000000,81452156,"['Whitney Houston', 'Angela Bassett', 'Loretta...",Forest Whitaker,https://images-na.ssl-images-amazon.com/images...
4,4,['Comedy'],11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,"['Sandollar Productions', 'Touchstone Pictures']",['US'],1995-02-10,...,5.7,173,Walt Disney Studios Motion Pictures,11134978,PG,0,76578911,"['Steve Martin', 'Diane Keaton', 'Martin Short']",Charles Shyer,https://images-na.ssl-images-amazon.com/images...

In [21]:
df.shape

(18875, 25)

In [22]:
df = df.merge(df_trailers[['imdb_id', 'trailer']], on=['imdb_id'], how='inner')
df.head()

,Unnamed: 0,genres,id,imdb_id,original_language,original_title,overview,production_companies,production_countries,release_date,...,vote_count,domestic_distributor,domestic_opening,mpaa,budget,revenue,actors,director,poster,trailer
0,2232,"['Drama', 'Action', 'Thriller', 'Crime']",19457,tt0138946,en,The Yards,"In the rail yards of Queens, contractors repai...","['Miramax Films', 'Industry Entertainment']",['US'],2000-04-27,...,98,Miramax,57339,R,0,924036,"['Mark Wahlberg', 'Joaquin Phoenix', 'Charlize...",James Gray,https://images-na.ssl-images-amazon.com/images...,https://youtu.be/udKtT5xkF_0
1,2543,['Comedy'],10471,tt0195945,en,Next Friday,"Ice Cube returns as Craig Jones, a streetwise ...",['New Line Cinema'],['US'],2000-01-12,...,145,New Line Cinema,14465156,R,11000000,59827328,"['Ice Cube', 'Mike Epps', 'Justin Pierce']",Steve Carr,https://images-na.ssl-images-amazon.com/images...,https://youtu.be/mKepqz19Qb0
2,2553,"['Comedy', 'Drama', 'Family']",17908,tt0156812,en,My Dog Skip,A shy boy is unable to make friends in Yazoo C...,"['Alcon Entertainment', 'Warner Bros.']",['US'],2000-01-14,...,71,Warner Bros.,56943,PG,7000000,35547761,"['Frankie Muniz', 'Diane Lane', 'Kevin Bacon']",Jay Russell,https://images-na.ssl-images-amazon.com/images...,https://youtu.be/KakRQzu6S3g
3,2571,"['Comedy', 'Drama', 'Family', 'Romance']",10472,tt0186975,en,Down to You,"College coeds in New York City, Al, the son of...",['Miramax Films'],['US'],2000-01-21,...,71,Miramax,7602507,PG-13,9000000,24419914,"['Freddie Prinze Jr.', 'Julia Stiles', 'Selma ...",Kris Isacsson,https://images-na.ssl-images-amazon.com/images...,https://youtu.be/1CKVi7AibI8
4,2575,"['Drama', 'Comedy']",75531,tt0141399,de,Isn't She Great,An unsuccessful over-the-top actress becomes a...,"['Universal Pictures', 'Mutual Film Company', ...",['US'],2000-01-28,...,14,Universal Pictures,1368705,R,36000000,3003296,"['Bette Midler', 'Nathan Lane', 'Stockard Chan...",Andrew Bergman,https://images-na.ssl-images-amazon.com/images...,https://youtu.be/MuKuIp8sNvw

In [23]:
df.shape

(6308, 26)

In [24]:
df.to_csv('./movie_dataset.csv')

In [ ]:
df[['imdb_id', 'trailer']].to_csv('')

        imdb_id                       trailer
0     tt0138946  https://youtu.be/udKtT5xkF_0
1     tt0195945  https://youtu.be/mKepqz19Qb0
2     tt0156812  https://youtu.be/KakRQzu6S3g
3     tt0186975  https://youtu.be/1CKVi7AibI8
4     tt0141399  https://youtu.be/MuKuIp8sNvw
...         ...                           ...
6303  tt5700224  https://youtu.be/jYHlRoADo1w
6304  tt5973626  https://youtu.be/_f728vAHmRg
6305  tt3062096  https://youtu.be/vXXAWJ4NCRo
6306  tt4361050  https://youtu.be/MJIcZGEjjwo
6307  tt1679335  https://youtu.be/PXrm5eU6HtY

[6308 rows x 2 columns]